function Contact () {
    return (
            <section className='contact-container' id='contact'>
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
                SMILEY FACE 😏
            </section>
    )
}

export default Contact